server:
  port: 3000
spring:
  application:
    name: jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: tobi
    password: tobi4ever
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
      show-sql: true